import type { NextPage } from "next";
import Head from "next/head";

const noEmail: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>
            Podany adres email nie istnieje w bazie danych. Spróbuj ponownie.
        </p>
            
        
      </>
    );
  };
  
  export default noEmail;
  