import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { z } from "zod";
import Form from "../components/Form/Form";
import Layout from "../components/Layout";
import Title from "../components/Title";
import { api } from "../utils/api";

export const editSelfSchema = z.object({
  name: z.string().min(2).max(20),
  email: z.string().email().max(30),
});

const EditSelf: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();
  console.log(session, status);
  const mutation = api.users.editSelf.useMutation();

  if (status === "loading") {
    return <div>Loading...</div>;
  }


  if (!session || !session.user) {
    return (
      <Layout>
        <p>You are not authenticated</p>
      </Layout>
    );
  }

  const handleSubmit = (data: z.infer<typeof editSelfSchema>) => {
    console.log(data);
    mutation.mutate( data );
    if (mutation.isSuccess) {
      console.log("Success!");
    }
    if (mutation.error) {
      console.log(mutation.error);
    }
  };

  return (
    <>
      <Head>
        <title>Work Planner 3000</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="m-6 grid">
          <Title>Change account details</Title>
          <div className="w-96">
            <Form
              schema={editSelfSchema}
              onSubmit={handleSubmit}
              renderAfter={() => (
                <button className="mt-2 w-full rounded bg-neutral-700 p-2.5 text-white transition hover:scale-105 hover:bg-stone-800">
                  Submit
                </button>
              )}
              defaultValues={{
                name: session.user.name ?? "",
                email: session.user.email ?? "",
              }}
              props={{
                name: {
                  placeholder: "ex: John Smith",
                  label: "Name",
                },
                email: {
                  placeholder: "ex: jsmith@company.com",
                  label: "Email",
                },
              }}
            />
            {mutation.isLoading && <p>Submitting</p>}
            {mutation.isSuccess && <p>Success!</p>}
            {mutation.error && <p>{mutation.error.message}</p>}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default EditSelf;
