import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { api } from "../utils/api";

const Configure: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
    const mutation = api.users.createSuperUser.useMutation();
    const [message, setMessage] = useState<string | undefined>(undefined);
    const handleClick = () => {
      mutation.mutate({ email: "terenoewt@gmail.com", name: "Dawid Drobny" });
      if (mutation.isSuccess) {
        setMessage("Success!");
      }
    };

    useEffect(() => {
      if (mutation.error)
        setMessage(mutation.error?.message);
      else if (mutation.isSuccess)
        setMessage("Success!");
    }, [mutation.error, mutation.isSuccess]);

    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>
            Enter your email and name to create your superuser account.
        </p>
        <button onClick={ handleClick }>button</button>
        {message && <p>{message}</p>}
      </>
    );
  };
  
  export default Configure;
  