import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";
import { Calendar, momentLocalizer } from 'react-big-calendar'
import Layout from "../components/Layout";
import { useRouter } from "next/router";
import moment from "moment";
import 'react-big-calendar/lib/css/react-big-calendar.css'

const Dashboard: NextPage = () => {

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
  const localizer = momentLocalizer(moment)
  const { data: sessionData } = useSession()
  const router = useRouter();
  const configRequired = api.users.configRequired.useQuery();
  const { data: projects } = api.projects.getAll.useQuery();
  console.log(projects);

  
  if (configRequired.data) {
    router.push("/configure")
    .catch((err) => {
      console.error(err);
    })
  }

  if (!sessionData) {
    return (
      <Layout>
        <p>Please log in to view this page</p>
      </Layout>
    )
  }


  return (
    <>
      <Head>
        <title>Work Planner 3000</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Calendar
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
          localizer={localizer}
          events={projects?.map((project) => {
            return {
              title: project.name,
              start: project.start,
              end: project.end,
              allDay: true,
            }
          } )}
          startAccessor="start"
          endAccessor="end"
          style={{ height: "100vmin" }} 
        />
      </Layout>
      
    </>
  );
};

export default Dashboard;
