import { Role } from "@prisma/client";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { z } from "zod";
import Form from "../../components/Form/Form";
import Layout from "../../components/Layout";
import Title from "../../components/Title";
import { api } from "../../utils/api";


export const addProjectSchema = z.object({
    name: z.string().min(2).max(20) ,
    start: z.coerce.date(),
    end: z.coerce.date(),
    members: z.array(z.string()).optional(),
})

const AddProject: NextPage = () => {

    const { data: session, status } = useSession();
    const { data: users } = api.users.getUsers.useQuery()
    const mutation = api.projects.addOne.useMutation()

    const handleSubmit = (data: z.infer<typeof addProjectSchema> ) => {
        mutation.mutate(data)
        if (mutation.isSuccess) {
            console.log("Success!")
        }
        if (mutation.error) {
            console.log(mutation.error)
        }
    }

    if (status === "loading" || !users) {
        return <div>Loading...</div>
    }


    if (session?.user && session.user?.permissions < 2) {
        return (
          <Layout>
            <p>You are not authorized to see this page</p>
          </Layout>
        )
    }

    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            
            <div className="grid m-6">
                <Title>Add a new Project</Title>
                <div className="w-96">
                    <Form 
                            schema={addProjectSchema}
                            onSubmit={handleSubmit}
                            renderAfter={() => <button className="w-full mt-2 bg-neutral-700 p-2.5 rounded text-white hover:bg-stone-800 hover:scale-105 transition" >Submit</button>}
                            props = {{
                                
                                members : {
                                    options: users.map(user => (user.email) ?? ""),
                                },

                                name: {
                                    placeholder: "ex: Project 1",
                                    label: "Name",
                                },
                            }}

                        />
                        {mutation.isError && <p className="text-red-500">{mutation.error?.message}</p>}
                        {mutation.isSuccess && <p className="text-green-500">Success!</p>}
                </div>  

            </div>
        </Layout>
            
        
      </>
    );
  };
  
  export default AddProject;
  