import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Layout from "../../components/Layout";
import { api } from "../../utils/api";

const Employees: NextPage = () => {

    const { data: session, status } = useSession();
    console.log(session, status)

    if (status === "loading") {
        return <div>Loading...</div>
    }

    if (status === "unauthenticated") {
        return (
          <Layout>
            <p>You need to be authenticated to see this page</p>
          </Layout>
        )
    }

    const { data: users } = api.users.getUsers.useQuery()


    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            {users?.map((user) => (
                <div key={user.id}>{user.name}  </div>
            ))}
        </Layout>
            
        
      </>
    );
  };
  
  export default Employees;
  